/*
 * CompararAñosChartPanel.java
 *
 * Created on 27 de agosto de 2007, 20:00
 */

package ingrGast.gui.chartsInsidePanel;

import ingrGast.gui.MainFrame;
import ingrGast.gui.charts.CompararAñosChart;
import ingrGast.interfaces.InsidePanel;
import ingrGast.management.Manager;
import java.awt.BorderLayout;
import java.util.Vector;

/**
 *
 * @author  Beñat
 */
public class CompararAñosChartPanel extends javax.swing.JPanel implements InsidePanel{
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 8539341383974428699L;
	
	/**
     * Creates new form CompararAñosChartPanel
     */
    public CompararAñosChartPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Generado  ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Comparar A\u00f1os"));
        jLabel1.setText("A\u00f1os a comparar:");

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Ingresos");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Gastos");
        jCheckBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox2ItemStateChanged(evt);
            }
        });

        jCheckBox3.setSelected(true);
        jCheckBox3.setText("Saldo");
        jCheckBox3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox3ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox3)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        if(jComboBox1.getSelectedItem() != null && jComboBox2.getSelectedItem() != null && compararChart != null){
            Vector<Vector<Double>> vBalance = this.manager.getBalanceAño(((Integer)jComboBox1.getSelectedItem()).intValue());
            Vector<Double> vIngr = vBalance.elementAt(0);
            vIngr.removeElementAt(vIngr.size()-1);
            Vector<Double> vGast = vBalance.elementAt(1);
            vGast.removeElementAt(vGast.size()-1);
            Vector<Double> vTot = vBalance.elementAt(2);
            vTot.removeElementAt(vTot.size()-1);
            
            Vector<Vector<Double>> vBalance2 = this.manager.getBalanceAño(((Integer)jComboBox2.getSelectedItem()).intValue());
            Vector<Double> vIngr2 = vBalance2.elementAt(0);
            vIngr2.removeElementAt(vIngr2.size()-1);
            Vector<Double> vGast2 = vBalance2.elementAt(1);
            vGast2.removeElementAt(vGast2.size()-1);
            Vector<Double> vTot2 = vBalance2.elementAt(2);
            vTot2.removeElementAt(vTot2.size()-1);
            
            compararChart.updateValues(((Integer)jComboBox1.getSelectedItem()).intValue(), vIngr, vGast, vTot, ((Integer)jComboBox2.getSelectedItem()).intValue(), vIngr2, vGast2, vTot2);
            compararChart.setTitle(((Integer)jComboBox1.getSelectedItem()).intValue(), ((Integer)jComboBox2.getSelectedItem()).intValue());
        }
    }//GEN-LAST:event_jComboBox2ItemStateChanged
    
    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if(jComboBox1.getSelectedItem() != null && jComboBox2.getSelectedItem() != null && compararChart != null){
            Vector<Vector<Double>> vBalance = this.manager.getBalanceAño(((Integer)jComboBox1.getSelectedItem()).intValue());
            Vector<Double> vIngr = vBalance.elementAt(0);
            vIngr.removeElementAt(vIngr.size()-1);
            Vector<Double> vGast = vBalance.elementAt(1);
            vGast.removeElementAt(vGast.size()-1);
            Vector<Double> vTot = vBalance.elementAt(2);
            vTot.removeElementAt(vTot.size()-1);
            
            Vector<Vector<Double>> vBalance2 = this.manager.getBalanceAño(((Integer)jComboBox2.getSelectedItem()).intValue());
            Vector<Double> vIngr2 = vBalance2.elementAt(0);
            vIngr2.removeElementAt(vIngr2.size()-1);
            Vector<Double> vGast2 = vBalance2.elementAt(1);
            vGast2.removeElementAt(vGast2.size()-1);
            Vector<Double> vTot2 = vBalance2.elementAt(2);
            vTot2.removeElementAt(vTot2.size()-1);
            
            compararChart.updateValues(((Integer)jComboBox1.getSelectedItem()).intValue(), vIngr, vGast, vTot, ((Integer)jComboBox2.getSelectedItem()).intValue(), vIngr2, vGast2, vTot2);
            compararChart.setTitle(((Integer)jComboBox1.getSelectedItem()).intValue(), ((Integer)jComboBox2.getSelectedItem()).intValue());
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged
    
    private void jCheckBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox3ItemStateChanged
        
    }//GEN-LAST:event_jCheckBox3ItemStateChanged
    
    private void jCheckBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox2ItemStateChanged
        
    }//GEN-LAST:event_jCheckBox2ItemStateChanged
    
    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        compararChart.setIngresosVisible(jCheckBox1.isSelected());
    }//GEN-LAST:event_jCheckBox1ItemStateChanged
    
    private void chargeComboBoxes(){
        Vector<Integer> vYears = this.manager.getAñosAsientos();
        this.jComboBox1.removeAllItems();
        this.jComboBox2.removeAllItems();
        for (Integer i: vYears){
            jComboBox1.addItem(i);
            jComboBox2.addItem(i);
        }
    }
    
    public void initData(MainFrame parent) {
        this.manager = parent.getManager();
        this.chargeComboBoxes();
        
        if (jComboBox1.getSelectedItem() != null && jComboBox2.getSelectedItem() != null){
            Vector<Vector<Double>> vBalance = this.manager.getBalanceAño(((Integer)jComboBox1.getSelectedItem()).intValue());
            Vector<Double> vIngr = vBalance.elementAt(0);
            vIngr.removeElementAt(vIngr.size()-1);
            Vector<Double> vGast = vBalance.elementAt(1);
            vGast.removeElementAt(vGast.size()-1);
            Vector<Double> vTot = vBalance.elementAt(2);
            vTot.removeElementAt(vTot.size()-1);
            
            Vector<Vector<Double>> vBalance2 = this.manager.getBalanceAño(((Integer)jComboBox2.getSelectedItem()).intValue());
            Vector<Double> vIngr2 = vBalance2.elementAt(0);
            vIngr2.removeElementAt(vIngr2.size()-1);
            Vector<Double> vGast2 = vBalance2.elementAt(1);
            vGast2.removeElementAt(vGast2.size()-1);
            Vector<Double> vTot2 = vBalance2.elementAt(2);
            vTot2.removeElementAt(vTot2.size()-1);
            
            compararChart = new CompararAñosChart(((Integer)jComboBox1.getSelectedItem()).intValue(), vIngr, vGast, vTot, ((Integer)jComboBox2.getSelectedItem()).intValue(), vIngr2, vGast2, vTot2);
            compararChart.setTitle(((Integer)jComboBox1.getSelectedItem()).intValue(), ((Integer)jComboBox2.getSelectedItem()).intValue());
        } else {
            compararChart = new CompararAñosChart(0, new Vector(), new Vector(), new Vector(), 0, new Vector(), new Vector(), new Vector());
        }
        jPanel1.add(compararChart.getChartPanel(), BorderLayout.CENTER);
    }
    
    public void updateData() {
        this.chargeComboBoxes();
    }
    
    public void disconnectResultSetTableModels() {
    }
    
    
    // Declaración de varibales -no modificar//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // Fin de declaración de variables//GEN-END:variables
    
    private Manager manager;
    private CompararAñosChart compararChart;
}
