/*
 * GraficosPanel.java
 *
 * Created on 24 de agosto de 2007, 19:50
 */

package ingrGast.gui.mainInsidePanels;

import ingrGast.gui.*;
import ingrGast.interfaces.InsidePanel;
import ingrGast.management.Manager;
import java.awt.CardLayout;
import java.awt.Component;

/**
 *
 * @author  Beñat
 */
public class GraficosPanel extends javax.swing.JPanel implements InsidePanel {
    
    /** Creates new form GraficosPanel */
    public GraficosPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Generado  ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        balanceChartPanel1 = new ingrGast.gui.chartsInsidePanel.BalanceChartPanel();
        compararAñosChartPanel1 = new ingrGast.gui.chartsInsidePanel.CompararAñosChartPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Gr\u00e1ficos"));
        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel1.add(balanceChartPanel1, "Balance");

        jPanel1.add(compararAñosChartPanel1, "Comparar");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Balance Anual", "Comparativa Anual" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        if(jList1.getSelectedIndex() == 0)
            ((CardLayout)jPanel1.getLayout()).show(jPanel1, "Balance");
        else if(jList1.getSelectedIndex() == 1)
            ((CardLayout)jPanel1.getLayout()).show(jPanel1, "Comparar");
    }//GEN-LAST:event_jList1ValueChanged
    
    
    // Declaración de varibales -no modificar//GEN-BEGIN:variables
    private ingrGast.gui.chartsInsidePanel.BalanceChartPanel balanceChartPanel1;
    private ingrGast.gui.chartsInsidePanel.CompararAñosChartPanel compararAñosChartPanel1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // Fin de declaración de variables//GEN-END:variables
    
    private MainFrame owner;
    private Manager manager;
    
    public void initData(MainFrame parent) {
        this.owner = parent;
        this.manager = this.owner.getManager();
        InsidePanel ip;
        for(Component c: jPanel1.getComponents()){
            ip = (InsidePanel)c;
            ip.initData(this.owner);
        }
    }
    
    public void updateData() {
        InsidePanel ip;
        for(Component c: jPanel1.getComponents()){
            ip = (InsidePanel)c;
            ip.updateData();
        }
    }
    
    public void disconnectResultSetTableModels() {
    }
}
