/*
 * BalanceChartPanel.java
 *
 * Created on 27 de agosto de 2007, 17:49
 */

package ingrGast.gui.chartsInsidePanel;

import ingrGast.gui.MainFrame;
import ingrGast.gui.charts.BalanceAnualChart;
import ingrGast.interfaces.InsidePanel;
import ingrGast.management.Manager;
import java.awt.BorderLayout;
import java.util.Vector;

/**
 *
 * @author  Beñat
 */
public class BalanceChartPanel extends javax.swing.JPanel implements InsidePanel{
    
    /** Creates new form BalanceChartPanel */
    public BalanceChartPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Generado  ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Balance Anual"));
        jLabel1.setText("A\u00f1o:");

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jPanel3.setLayout(new java.awt.BorderLayout());

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Ingresos");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Gastos");
        jCheckBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox2ItemStateChanged(evt);
            }
        });

        jCheckBox3.setSelected(true);
        jCheckBox3.setText("Saldo");
        jCheckBox3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox3ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox3)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void jCheckBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox3ItemStateChanged
        balanceChart.setSaldoVisible(jCheckBox3.isSelected());
    }//GEN-LAST:event_jCheckBox3ItemStateChanged
    
    private void jCheckBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox2ItemStateChanged
        balanceChart.setGastosVisible(jCheckBox2.isSelected());
    }//GEN-LAST:event_jCheckBox2ItemStateChanged
    
    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        balanceChart.setIngresosVisible(jCheckBox1.isSelected());
    }//GEN-LAST:event_jCheckBox1ItemStateChanged
    
    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if(jComboBox1.getSelectedItem() != null && balanceChart != null){
            Vector<Vector<Double>> vBalance = this.manager.getBalanceAño(((Integer)jComboBox1.getSelectedItem()).intValue());
            Vector<Double> vIngr = vBalance.elementAt(0);
            vIngr.removeElementAt(vIngr.size()-1);
            Vector<Double> vGast = vBalance.elementAt(1);
            vGast.removeElementAt(vGast.size()-1);
            for(Double d: vGast){
                if(d.doubleValue() < 0)
                    vGast.setElementAt(new Double(d.doubleValue() * (-1)), vGast.indexOf(d));
            }
            Vector<Double> vTot = vBalance.elementAt(2);
            vTot.removeElementAt(vTot.size()-1);
            balanceChart.updateValues(vIngr, vGast, vTot);
            balanceChart.addSubtitle(((Integer)jComboBox1.getSelectedItem()).intValue());
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged
    
    
    // Declaración de varibales -no modificar//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    // Fin de declaración de variables//GEN-END:variables
    
    private Manager manager;
    private BalanceAnualChart balanceChart;
    
    private void chargeComboBox(){
        Vector<Integer> vYears = this.manager.getAñosAsientos();
        this.jComboBox1.removeAllItems();
        for (Integer i: vYears)
            jComboBox1.addItem(i);
    }
    
    public void initData(MainFrame parent) {
        this.manager = parent.getManager();
        this.chargeComboBox();
        
        Vector<Vector<Double>> vBalance = this.manager.getBalanceAño(((Integer)jComboBox1.getSelectedItem()).intValue());
        Vector<Double> vIngr = vBalance.elementAt(0);
        vIngr.removeElementAt(vIngr.size()-1);
        Vector<Double> vGast = vBalance.elementAt(1);
        vGast.removeElementAt(vGast.size()-1);
        for(Double d: vGast){
            if(d.doubleValue() < 0)
                vGast.setElementAt(new Double(d.doubleValue() * (-1)), vGast.indexOf(d));
        }
        Vector<Double> vTot = vBalance.elementAt(2);
        vTot.removeElementAt(vTot.size()-1);
        
        balanceChart = new BalanceAnualChart(vIngr, vGast, vTot);
        balanceChart.addSubtitle(((Integer)jComboBox1.getSelectedItem()).intValue());
        jPanel3.add(balanceChart.getChartPanel(), BorderLayout.CENTER);
    }
    
    public void updateData() {
        this.chargeComboBox();
    }
    
    public void disconnectResultSetTableModels() {
    }
    
}
